/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminDashboardRouteRouteImport } from './routes/(admin)/dashboard/route'
import { Route as adminLiveviewRouteRouteImport } from './routes/(admin)/liveview/route'
import { Route as publicLombaRouteRouteImport } from './routes/(public)/lomba/route'
import { Route as adminDashboardIndexRouteImport } from './routes/(admin)/dashboard/index'
import { Route as adminDashboardConfigPasienRouteRouteImport } from './routes/(admin)/dashboard/config/pasien/route'
import { Route as adminDashboardContestIndexRouteImport } from './routes/(admin)/dashboard/contest/index'
import { Route as adminDashboardContestContestIdRouteRouteImport } from './routes/(admin)/dashboard/contest/$contestId/route'
import { Route as adminDashboardContestRekapRouteRouteImport } from './routes/(admin)/dashboard/contest/rekap/route'
import { Route as adminDashboardContestTambahRouteRouteImport } from './routes/(admin)/dashboard/contest/tambah/route'
import { Route as adminDashboardMasterPasienRouteRouteImport } from './routes/(admin)/dashboard/master/pasien/route'
import { Route as adminDashboardMasterPeriodeRouteRouteImport } from './routes/(admin)/dashboard/master/periode/route'
import { Route as adminDashboardSystemRoleRouteRouteImport } from './routes/(admin)/dashboard/system/role/route'
import { Route as adminDashboardSystemUserRouteRouteImport } from './routes/(admin)/dashboard/system/user/route'
import { Route as adminDashboardMasterKasusIndexRouteImport } from './routes/(admin)/dashboard/master/kasus/index'
import { Route as adminDashboardMasterKasusTambahRouteRouteImport } from './routes/(admin)/dashboard/master/kasus/tambah/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDashboardRouteRoute = adminDashboardRouteRouteImport.update({
  id: '/(admin)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLiveviewRouteRoute = adminLiveviewRouteRouteImport.update({
  id: '/(admin)/liveview',
  path: '/liveview',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLombaRouteRoute = publicLombaRouteRouteImport.update({
  id: '/(public)/lomba',
  path: '/lomba',
  getParentRoute: () => rootRouteImport,
} as any)
const adminDashboardIndexRoute = adminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminDashboardRouteRoute,
} as any)
const adminDashboardConfigPasienRouteRoute =
  adminDashboardConfigPasienRouteRouteImport.update({
    id: '/config/pasien',
    path: '/config/pasien',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardContestIndexRoute =
  adminDashboardContestIndexRouteImport.update({
    id: '/contest/',
    path: '/contest/',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardContestContestIdRouteRoute =
  adminDashboardContestContestIdRouteRouteImport.update({
    id: '/contest/$contestId',
    path: '/contest/$contestId',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardContestRekapRouteRoute =
  adminDashboardContestRekapRouteRouteImport.update({
    id: '/contest/rekap',
    path: '/contest/rekap',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardContestTambahRouteRoute =
  adminDashboardContestTambahRouteRouteImport.update({
    id: '/contest/tambah',
    path: '/contest/tambah',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardMasterPasienRouteRoute =
  adminDashboardMasterPasienRouteRouteImport.update({
    id: '/master/pasien',
    path: '/master/pasien',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardMasterPeriodeRouteRoute =
  adminDashboardMasterPeriodeRouteRouteImport.update({
    id: '/master/periode',
    path: '/master/periode',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardSystemRoleRouteRoute =
  adminDashboardSystemRoleRouteRouteImport.update({
    id: '/system/role',
    path: '/system/role',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardSystemUserRouteRoute =
  adminDashboardSystemUserRouteRouteImport.update({
    id: '/system/user',
    path: '/system/user',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardMasterKasusIndexRoute =
  adminDashboardMasterKasusIndexRouteImport.update({
    id: '/master/kasus/',
    path: '/master/kasus/',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)
const adminDashboardMasterKasusTambahRouteRoute =
  adminDashboardMasterKasusTambahRouteRouteImport.update({
    id: '/master/kasus/tambah',
    path: '/master/kasus/tambah',
    getParentRoute: () => adminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof adminDashboardRouteRouteWithChildren
  '/liveview': typeof adminLiveviewRouteRoute
  '/lomba': typeof publicLombaRouteRoute
  '/dashboard/': typeof adminDashboardIndexRoute
  '/dashboard/config/pasien': typeof adminDashboardConfigPasienRouteRoute
  '/dashboard/contest/$contestId': typeof adminDashboardContestContestIdRouteRoute
  '/dashboard/contest/rekap': typeof adminDashboardContestRekapRouteRoute
  '/dashboard/contest/tambah': typeof adminDashboardContestTambahRouteRoute
  '/dashboard/master/pasien': typeof adminDashboardMasterPasienRouteRoute
  '/dashboard/master/periode': typeof adminDashboardMasterPeriodeRouteRoute
  '/dashboard/system/role': typeof adminDashboardSystemRoleRouteRoute
  '/dashboard/system/user': typeof adminDashboardSystemUserRouteRoute
  '/dashboard/contest/': typeof adminDashboardContestIndexRoute
  '/dashboard/master/kasus/tambah': typeof adminDashboardMasterKasusTambahRouteRoute
  '/dashboard/master/kasus/': typeof adminDashboardMasterKasusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/liveview': typeof adminLiveviewRouteRoute
  '/lomba': typeof publicLombaRouteRoute
  '/dashboard': typeof adminDashboardIndexRoute
  '/dashboard/config/pasien': typeof adminDashboardConfigPasienRouteRoute
  '/dashboard/contest/$contestId': typeof adminDashboardContestContestIdRouteRoute
  '/dashboard/contest/rekap': typeof adminDashboardContestRekapRouteRoute
  '/dashboard/contest/tambah': typeof adminDashboardContestTambahRouteRoute
  '/dashboard/master/pasien': typeof adminDashboardMasterPasienRouteRoute
  '/dashboard/master/periode': typeof adminDashboardMasterPeriodeRouteRoute
  '/dashboard/system/role': typeof adminDashboardSystemRoleRouteRoute
  '/dashboard/system/user': typeof adminDashboardSystemUserRouteRoute
  '/dashboard/contest': typeof adminDashboardContestIndexRoute
  '/dashboard/master/kasus/tambah': typeof adminDashboardMasterKasusTambahRouteRoute
  '/dashboard/master/kasus': typeof adminDashboardMasterKasusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)/dashboard': typeof adminDashboardRouteRouteWithChildren
  '/(admin)/liveview': typeof adminLiveviewRouteRoute
  '/(public)/lomba': typeof publicLombaRouteRoute
  '/(admin)/dashboard/': typeof adminDashboardIndexRoute
  '/(admin)/dashboard/config/pasien': typeof adminDashboardConfigPasienRouteRoute
  '/(admin)/dashboard/contest/$contestId': typeof adminDashboardContestContestIdRouteRoute
  '/(admin)/dashboard/contest/rekap': typeof adminDashboardContestRekapRouteRoute
  '/(admin)/dashboard/contest/tambah': typeof adminDashboardContestTambahRouteRoute
  '/(admin)/dashboard/master/pasien': typeof adminDashboardMasterPasienRouteRoute
  '/(admin)/dashboard/master/periode': typeof adminDashboardMasterPeriodeRouteRoute
  '/(admin)/dashboard/system/role': typeof adminDashboardSystemRoleRouteRoute
  '/(admin)/dashboard/system/user': typeof adminDashboardSystemUserRouteRoute
  '/(admin)/dashboard/contest/': typeof adminDashboardContestIndexRoute
  '/(admin)/dashboard/master/kasus/tambah': typeof adminDashboardMasterKasusTambahRouteRoute
  '/(admin)/dashboard/master/kasus/': typeof adminDashboardMasterKasusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/liveview'
    | '/lomba'
    | '/dashboard/'
    | '/dashboard/config/pasien'
    | '/dashboard/contest/$contestId'
    | '/dashboard/contest/rekap'
    | '/dashboard/contest/tambah'
    | '/dashboard/master/pasien'
    | '/dashboard/master/periode'
    | '/dashboard/system/role'
    | '/dashboard/system/user'
    | '/dashboard/contest/'
    | '/dashboard/master/kasus/tambah'
    | '/dashboard/master/kasus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/liveview'
    | '/lomba'
    | '/dashboard'
    | '/dashboard/config/pasien'
    | '/dashboard/contest/$contestId'
    | '/dashboard/contest/rekap'
    | '/dashboard/contest/tambah'
    | '/dashboard/master/pasien'
    | '/dashboard/master/periode'
    | '/dashboard/system/role'
    | '/dashboard/system/user'
    | '/dashboard/contest'
    | '/dashboard/master/kasus/tambah'
    | '/dashboard/master/kasus'
  id:
    | '__root__'
    | '/'
    | '/(admin)/dashboard'
    | '/(admin)/liveview'
    | '/(public)/lomba'
    | '/(admin)/dashboard/'
    | '/(admin)/dashboard/config/pasien'
    | '/(admin)/dashboard/contest/$contestId'
    | '/(admin)/dashboard/contest/rekap'
    | '/(admin)/dashboard/contest/tambah'
    | '/(admin)/dashboard/master/pasien'
    | '/(admin)/dashboard/master/periode'
    | '/(admin)/dashboard/system/role'
    | '/(admin)/dashboard/system/user'
    | '/(admin)/dashboard/contest/'
    | '/(admin)/dashboard/master/kasus/tambah'
    | '/(admin)/dashboard/master/kasus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminDashboardRouteRoute: typeof adminDashboardRouteRouteWithChildren
  adminLiveviewRouteRoute: typeof adminLiveviewRouteRoute
  publicLombaRouteRoute: typeof publicLombaRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/dashboard': {
      id: '/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/liveview': {
      id: '/(admin)/liveview'
      path: '/liveview'
      fullPath: '/liveview'
      preLoaderRoute: typeof adminLiveviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/lomba': {
      id: '/(public)/lomba'
      path: '/lomba'
      fullPath: '/lomba'
      preLoaderRoute: typeof publicLombaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/dashboard/': {
      id: '/(admin)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof adminDashboardIndexRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/config/pasien': {
      id: '/(admin)/dashboard/config/pasien'
      path: '/config/pasien'
      fullPath: '/dashboard/config/pasien'
      preLoaderRoute: typeof adminDashboardConfigPasienRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/contest/': {
      id: '/(admin)/dashboard/contest/'
      path: '/contest'
      fullPath: '/dashboard/contest/'
      preLoaderRoute: typeof adminDashboardContestIndexRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/contest/$contestId': {
      id: '/(admin)/dashboard/contest/$contestId'
      path: '/contest/$contestId'
      fullPath: '/dashboard/contest/$contestId'
      preLoaderRoute: typeof adminDashboardContestContestIdRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/contest/rekap': {
      id: '/(admin)/dashboard/contest/rekap'
      path: '/contest/rekap'
      fullPath: '/dashboard/contest/rekap'
      preLoaderRoute: typeof adminDashboardContestRekapRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/contest/tambah': {
      id: '/(admin)/dashboard/contest/tambah'
      path: '/contest/tambah'
      fullPath: '/dashboard/contest/tambah'
      preLoaderRoute: typeof adminDashboardContestTambahRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/master/pasien': {
      id: '/(admin)/dashboard/master/pasien'
      path: '/master/pasien'
      fullPath: '/dashboard/master/pasien'
      preLoaderRoute: typeof adminDashboardMasterPasienRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/master/periode': {
      id: '/(admin)/dashboard/master/periode'
      path: '/master/periode'
      fullPath: '/dashboard/master/periode'
      preLoaderRoute: typeof adminDashboardMasterPeriodeRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/system/role': {
      id: '/(admin)/dashboard/system/role'
      path: '/system/role'
      fullPath: '/dashboard/system/role'
      preLoaderRoute: typeof adminDashboardSystemRoleRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/system/user': {
      id: '/(admin)/dashboard/system/user'
      path: '/system/user'
      fullPath: '/dashboard/system/user'
      preLoaderRoute: typeof adminDashboardSystemUserRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/master/kasus/': {
      id: '/(admin)/dashboard/master/kasus/'
      path: '/master/kasus'
      fullPath: '/dashboard/master/kasus/'
      preLoaderRoute: typeof adminDashboardMasterKasusIndexRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
    '/(admin)/dashboard/master/kasus/tambah': {
      id: '/(admin)/dashboard/master/kasus/tambah'
      path: '/master/kasus/tambah'
      fullPath: '/dashboard/master/kasus/tambah'
      preLoaderRoute: typeof adminDashboardMasterKasusTambahRouteRouteImport
      parentRoute: typeof adminDashboardRouteRoute
    }
  }
}

interface adminDashboardRouteRouteChildren {
  adminDashboardIndexRoute: typeof adminDashboardIndexRoute
  adminDashboardConfigPasienRouteRoute: typeof adminDashboardConfigPasienRouteRoute
  adminDashboardContestContestIdRouteRoute: typeof adminDashboardContestContestIdRouteRoute
  adminDashboardContestRekapRouteRoute: typeof adminDashboardContestRekapRouteRoute
  adminDashboardContestTambahRouteRoute: typeof adminDashboardContestTambahRouteRoute
  adminDashboardMasterPasienRouteRoute: typeof adminDashboardMasterPasienRouteRoute
  adminDashboardMasterPeriodeRouteRoute: typeof adminDashboardMasterPeriodeRouteRoute
  adminDashboardSystemRoleRouteRoute: typeof adminDashboardSystemRoleRouteRoute
  adminDashboardSystemUserRouteRoute: typeof adminDashboardSystemUserRouteRoute
  adminDashboardContestIndexRoute: typeof adminDashboardContestIndexRoute
  adminDashboardMasterKasusTambahRouteRoute: typeof adminDashboardMasterKasusTambahRouteRoute
  adminDashboardMasterKasusIndexRoute: typeof adminDashboardMasterKasusIndexRoute
}

const adminDashboardRouteRouteChildren: adminDashboardRouteRouteChildren = {
  adminDashboardIndexRoute: adminDashboardIndexRoute,
  adminDashboardConfigPasienRouteRoute: adminDashboardConfigPasienRouteRoute,
  adminDashboardContestContestIdRouteRoute:
    adminDashboardContestContestIdRouteRoute,
  adminDashboardContestRekapRouteRoute: adminDashboardContestRekapRouteRoute,
  adminDashboardContestTambahRouteRoute: adminDashboardContestTambahRouteRoute,
  adminDashboardMasterPasienRouteRoute: adminDashboardMasterPasienRouteRoute,
  adminDashboardMasterPeriodeRouteRoute: adminDashboardMasterPeriodeRouteRoute,
  adminDashboardSystemRoleRouteRoute: adminDashboardSystemRoleRouteRoute,
  adminDashboardSystemUserRouteRoute: adminDashboardSystemUserRouteRoute,
  adminDashboardContestIndexRoute: adminDashboardContestIndexRoute,
  adminDashboardMasterKasusTambahRouteRoute:
    adminDashboardMasterKasusTambahRouteRoute,
  adminDashboardMasterKasusIndexRoute: adminDashboardMasterKasusIndexRoute,
}

const adminDashboardRouteRouteWithChildren =
  adminDashboardRouteRoute._addFileChildren(adminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminDashboardRouteRoute: adminDashboardRouteRouteWithChildren,
  adminLiveviewRouteRoute: adminLiveviewRouteRoute,
  publicLombaRouteRoute: publicLombaRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
